### ISSUE TITLE
SDK version error

### ISSUE THREAD

**Issue by deep01code** [pulyaevskiy/dart-kafka#18]
Hi,

I am not able to use this package due to the following error. 

```
The current Dart SDK version is 2.8.3.



Because dummy_app depends on kafka from git which requires SDK version >=1.12.0 <2.0.0, version solving failed.
pub
```

what I can do to fix this issue.

Thanks in Advance

**Comment by larryaasen** [comment]
If you are using the `master` branch, it is still using Dart >=1.12.0 <2.0.0, and your Dart version is 2.8.3. You may want to try the experimental branch `kafka-0.10` that supports Dart >=2.1.0 < 3.0.0.

**Comment by deep01code** [comment]
Thanks a lot, I just added the branch and it works fine. 

incase if anyone would like to know how to add a branch for git dependency here is example
```
dependencies:
  package1:
    git:
      url: git://github.com/flutter/packages.git
      ref: some-branch
```
